services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations monitor &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python setup_tasks.py &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" &&
             gunicorn config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  celery_beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
