# Generated by Django 5.0.3 on 2026-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Token from @BotFather', max_length=255, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Chat ID to send alerts to', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='OpenRouterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('balance_threshold', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_alerted', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_or_url', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='For TCP check', null=True)),
                ('check_type', models.CharField(choices=[('ping', 'ICMP Ping'), ('tcp', 'TCP Port Check'), ('http', 'HTTP GET')], default='ping', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socks5Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SOCKS5 Proxy',
                'verbose_name_plural': 'SOCKS5 Proxies',
            },
        ),
    ]
