# Generated by Django 5.0.3 on 2026-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='status_message_id',
            field=models.IntegerField(blank=True, help_text='ID of the dashboard message to edit', null=True),
        ),
    ]
