# Generated by Django 5.0.3 on 2026-03-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_globalsettings_status_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverendpoint',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Last response time in ms', null=True),
        ),
        migrations.AddField(
            model_name='socks5proxy',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Last response time in ms', null=True),
        ),
    ]
